feature/w-12393084 renewal of invalid sessions
Phennecs/wsc pull request #5
Opened 2023-01-17 22:04 UTC by jaizpuru-sf

# Description

Have the retryTemplate renew session upon INVALID_SESSION_ID errors found 

# Resolves

[W-12393084](https://gus.lightning.force.com/a07EE00001JYIvqYAH)

# Testing

New unit tests added. Pending QA of a SNAPSHOT build on a dev org

## Tests in the PR

- [ ] Manual Tests
- [x] Unit Tests
- [ ] Integration Tests

2023-01-17 22:11 UTC, barrerajuanjose approved these changes
LGTM!

2023-01-18 18:24 UTC, ztaylor797 requested changes
Left two small comments! Thank you. Nice work.

2023-01-18 18:24 UTC, ztaylor797 commented on src/main/java/com/sforce/ws/transport/ApiRetryTemplate.java
> +                        throw new AsyncApiException("Cant renew session", AsyncExceptionCode.ClientInputError, ex);
"Cant" -> "Can't" and perhaps note that this is referring to a Salesforce session? Just for clarity?

2023-01-18 18:24 UTC, ztaylor797 commented on src/main/java/com/sforce/ws/transport/ApiRetryTemplate.java
> +                        config.getSessionRenewer().renewSession(config);
The session renewer is not required for any arbitrary consumer of this lib, so I think we should add a null check here or elsewhere for that case.

2023-01-18 20:24 UTC, ztaylor797 approved these changes
LGTM!

2023-01-18 20:30 UTC, merged