Feature/w 12285553 add exceptions to retry
Phennecs/wsc pull request #6
Opened 2023-02-12 20:43 UTC by barrerajuanjose

# Description
Add retryable messages option thus it is easier to retry [this kind of errors](https://www.google.com/url?q=https://trailblazer.salesforce.com/issues_view?id%3Da1p4V000002e0HyQAI%26title%3Dintermittent-unexpected-internal-servlet-state-during-soap-and-bulk-api-requests&sa=D&source=editors&ust=1676080657200528&usg=AOvVaw3VoSUUa1W5icHvaJio4Z_w).

# Resolves

[W-12285553](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00001IOeF2YAL/view)

# Testing

Here you place all the testing you completed to ensure that the issue was corrected.

## Tests in the PR

- [X] Manual Tests
- [X] Unit Tests
- [X] Integration Tests

2023-02-13 14:34 UTC, jaizpuru-sf requested changes
Thanks for taking care of this JJ! I have a couple of comments:
- Have you considered extending this so that it also covers Partner API? The Exceptions seems to differ across services, according to the document you linked.
- This solution seems to rely heavily on the error message itself, which is potentially subject to change. Some alternatives I can think of: 
    - Rely on the AsyncApiException.exceptionCode (at least for BulkApi), which we already handle in the RetryTemplate.
    - Consider covering the whole class (i.e. SoapFaultException)
    - Keep the message matching approach, but use shorter substrings of the actual messages (i.e.: "Unexpected internal servlet state").

2023-02-13 18:38 UTC, barrerajuanjose commented
That makes sense to me @jaizpuru-sf .
I will create a WI about it. Do you think that in that WI we should move this retry logic to salesforce-jdbc repo?

2023-02-13 22:03 UTC, ztaylor797 commented
> Is it required for 2.5.0? If this error we're seeing is because of some sort of regression, then yes, of course. If not, probably 2.6

Agree with this logic.

> About moving to salesforce-jdbc: I think we'd be better of using stock wsc (or as close as we can get). But I'm also not sure if/how we could move all the retry logic downstream without adding much more overall code volume, which we also don't want.

Stock would be a bit difficult with the interceptors for the arbiter. Not sure how we would handle those.

2023-02-13 22:03 UTC, ztaylor797 requested changes
LGTM other than existing comments from Juan.

2023-02-15 14:19 UTC, jaizpuru-sf commented on src/main/java/com/sforce/async/BulkConnection.java
> +                        "Server error returned in unknown format " + typeDesc + ". Body: " + body,
Makes sense! Addressed

2023-02-15 14:19 UTC, jaizpuru-sf commented on src/main/java/com/sforce/async/BulkConnection.java
> +                    body = body.length() <= 250 ? body : body.substring(0, 250) + "...";
The thing is, wsc doesn't depend on Apache commons-lang, and I couldn't find anything equivalent

2023-02-15 14:37 UTC, ztaylor797 commented
That's fine then. Only other thing I might mention is that there is a
single character ellipsis if you wanted to use that.

On Wed, Feb 15, 2023, 8:20 AM jaizpuru-sf ***@***.***> wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In src/main/java/com/sforce/async/BulkConnection.java
> <https://github.com/Phennecs/wsc/pull/6#discussion_r1107186896>:
>
> > @@ -196,7 +201,17 @@ static void parseAndThrowException(InputStream in, ContentType type) throws Asyn
>                  JsonParser parser = factory.createJsonParser(in);
>                  exception = parser.readValueAs(AsyncApiException.class);
>              } else {
> -                throw new AsyncApiException("Server error returned in unknown format", AsyncExceptionCode.ClientInputError);
> +                String body = "?";
> +                String typeDesc = type == null ? "?" : type.name();
> +                try {
> +                    body = new String(FileUtil.toBytes(in), StandardCharsets.UTF_8);
> +                    body = body.length() <= 250 ? body : body.substring(0, 250) + "...";
>
> The thing is, wsc doesn't depend on Apache commons-lang, and I couldn't
> find anything equivalent
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Phennecs/wsc/pull/6#discussion_r1107186896>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AGT4EDEDBNMXRYEBZM7ZO43WXTQY7ANCNFSM6AAAAAAUZRVJKM>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-02-17 18:44 UTC, merged